[project]
name = "marimo-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fire>=0.7.1",
    "folium>=0.20.0",
    "geopandas>=1.1.1",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "marimo>=0.18.0",
]
